interface RoleOption {
  value: string;
  label: string;
}

const roles: RoleOption[] = [
  { value: "software-developer", label: "Software Developer" },
  { value: "frontend-developer", label: "Frontend Developer" },
  { value: "backend-developer", label: "Backend Developer" },
  { value: "full-stack-developer", label: "Full Stack Developer" },
  { value: "mobile-app-developer", label: "Mobile App Developer" },
  { value: "ui-ux-designer", label: "UI/UX Designer" },
  { value: "devops-engineer", label: "DevOps Engineer" },
  { value: "cloud-engineer", label: "Cloud Engineer" },
  { value: "data-analyst", label: "Data Analyst" },
  { value: "data-scientist", label: "Data Scientist" },
  { value: "database-administrator", label: "Database Administrator" },
  { value: "qa-tester", label: "QA Tester" },
  { value: "automation-engineer", label: "Automation Engineer" },
  { value: "machine-learning-engineer", label: "Machine Learning Engineer" },
  { value: "ai-engineer", label: "AI Engineer" },
  { value: "system-administrator", label: "System Administrator" },
  { value: "it-support-specialist", label: "IT Support Specialist" },
  { value: "cybersecurity-analyst", label: "Cybersecurity Analyst" },
  { value: "product-manager", label: "Product Manager" },
  { value: "technical-lead", label: "Technical Lead" },
  { value: "solution-architect", label: "Solution Architect" },
  { value: "business-analyst", label: "Business Analyst" },
  { value: "operations-analyst", label: "Operations Analyst" },
  { value: "financial-analyst", label: "Financial Analyst" },
  { value: "project-manager", label: "Project Manager" },
  { value: "scrum-master", label: "Scrum Master" },
  { value: "product-owner", label: "Product Owner" },
  { value: "consultant", label: "Consultant" },
  { value: "risk-analyst", label: "Risk Analyst" },
  { value: "research-analyst", label: "Research Analyst" },
  { value: "strategy-associate", label: "Strategy Associate" },
  { value: "hr-manager", label: "HR Manager" },
  { value: "recruiter", label: "Recruiter" },
  { value: "talent-acquisition-specialist", label: "Talent Acquisition Specialist" },
  { value: "training-coordinator", label: "Training Coordinator" },
  { value: "office-administrator", label: "Office Administrator" },
  { value: "hr-executive", label: "HR Executive" },
  { value: "compensation-benefits-analyst", label: "Compensation and Benefits Analyst" },
  { value: "marketing-manager", label: "Marketing Manager" },
  { value: "digital-marketing-executive", label: "Digital Marketing Executive" },
  { value: "seo-specialist", label: "SEO Specialist" },
  { value: "content-writer", label: "Content Writer" },
  { value: "social-media-manager", label: "Social Media Manager" },
  { value: "sales-executive", label: "Sales Executive" },
  { value: "business-development-manager", label: "Business Development Manager" },
  { value: "account-manager", label: "Account Manager" },
  { value: "brand-strategist", label: "Brand Strategist" },
  { value: "customer-success-manager", label: "Customer Success Manager" },
  { value: "accountant", label: "Accountant" },
  { value: "finance-manager", label: "Finance Manager" },
  { value: "auditor", label: "Auditor" },
  { value: "tax-consultant", label: "Tax Consultant" },
  { value: "payroll-specialist", label: "Payroll Specialist" },
  { value: "budget-analyst", label: "Budget Analyst" },
  { value: "ceo", label: "Chief Executive Officer (CEO)" },
  { value: "cto", label: "Chief Technology Officer (CTO)" },
  { value: "cfo", label: "Chief Financial Officer (CFO)" },
  { value: "coo", label: "Chief Operating Officer (COO)" },
  { value: "engineering-manager", label: "Engineering Manager" },
  { value: "team-lead", label: "Team Lead" },
  { value: "director-of-operations", label: "Director of Operations" },
  { value: "customer-support-executive", label: "Customer Support Executive" },
  { value: "technical-support-engineer", label: "Technical Support Engineer" },
  { value: "network-engineer", label: "Network Engineer" },
  { value: "procurement-specialist", label: "Procurement Specialist" },
  { value: "legal-advisor", label: "Legal Advisor" },
  { value: "quality-assurance-manager", label: "Quality Assurance Manager" },
  { value: "training-specialist", label: "Training Specialist" }
];

export default roles;
