export interface RoleOption {
  value: string;
  label: string;
}

const roles: RoleOption[] = [
  { value: "Software Developer", label: "Software Developer" },
  { value: "Frontend Developer", label: "Frontend Developer" },
  { value: "Backend Developer", label: "Backend Developer" },
  { value: "Full Stack Developer", label: "Full Stack Developer" },
  { value: "Mobile App Developer", label: "Mobile App Developer" },
  { value: "UI/UX Designer", label: "UI/UX Designer" },
  { value: "DevOps Engineer", label: "DevOps Engineer" },
  { value: "Cloud Engineer", label: "Cloud Engineer" },
  { value: "Data Analyst", label: "Data Analyst" },
  { value: "Data Scientist", label: "Data Scientist" },
  { value: "Database Administrator", label: "Database Administrator" },
  { value: "QA Tester", label: "QA Tester" },
  { value: "Automation Engineer", label: "Automation Engineer" },
  { value: "Machine Learning Engineer", label: "Machine Learning Engineer" },
  { value: "AI Engineer", label: "AI Engineer" },
  { value: "System Administrator", label: "System Administrator" },
  { value: "IT Support Specialist", label: "IT Support Specialist" },
  { value: "Cybersecurity Analyst", label: "Cybersecurity Analyst" },
  { value: "Product Manager", label: "Product Manager" },
  { value: "Technical Lead", label: "Technical Lead" },
  { value: "Solution Architect", label: "Solution Architect" },
  { value: "Business Analyst", label: "Business Analyst" },
  { value: "Operations Analyst", label: "Operations Analyst" },
  { value: "Financial Analyst", label: "Financial Analyst" },
  { value: "Project Manager", label: "Project Manager" },
  { value: "Scrum Master", label: "Scrum Master" },
  { value: "Product Owner", label: "Product Owner" },
  { value: "Consultant", label: "Consultant" },
  { value: "Risk Analyst", label: "Risk Analyst" },
  { value: "Research Analyst", label: "Research Analyst" },
  { value: "Strategy Associate", label: "Strategy Associate" },
  { value: "HR Manager", label: "HR Manager" },
  { value: "Recruiter", label: "Recruiter" },
  { value: "Talent Acquisition Specialist", label: "Talent Acquisition Specialist" },
  { value: "Training Coordinator", label: "Training Coordinator" },
  { value: "Office Administrator", label: "Office Administrator" },
  { value: "HR Executive", label: "HR Executive" },
  { value: "Compensation and Benefits Analyst", label: "Compensation and Benefits Analyst" },
  { value: "Marketing Manager", label: "Marketing Manager" },
  { value: "Digital Marketing Executive", label: "Digital Marketing Executive" },
  { value: "SEO Specialist", label: "SEO Specialist" },
  { value: "Content Writer", label: "Content Writer" },
  { value: "Social Media Manager", label: "Social Media Manager" },
  { value: "Sales Executive", label: "Sales Executive" },
  { value: "Business Development Manager", label: "Business Development Manager" },
  { value: "Account Manager", label: "Account Manager" },
  { value: "Brand Strategist", label: "Brand Strategist" },
  { value: "Customer Success Manager", label: "Customer Success Manager" },
  { value: "Accountant", label: "Accountant" },
  { value: "Finance Manager", label: "Finance Manager" },
  { value: "Auditor", label: "Auditor" },
  { value: "Tax Consultant", label: "Tax Consultant" },
  { value: "Payroll Specialist", label: "Payroll Specialist" },
  { value: "Budget Analyst", label: "Budget Analyst" },
  { value: "Chief Executive Officer (CEO)", label: "Chief Executive Officer (CEO)" },
  { value: "Chief Technology Officer (CTO)", label: "Chief Technology Officer (CTO)" },
  { value: "Chief Financial Officer (CFO)", label: "Chief Financial Officer (CFO)" },
  { value: "Chief Operating Officer (COO)", label: "Chief Operating Officer (COO)" },
  { value: "Engineering Manager", label: "Engineering Manager" },
  { value: "Team Lead", label: "Team Lead" },
  { value: "Director of Operations", label: "Director of Operations" },
  { value: "Customer Support Executive", label: "Customer Support Executive" },
  { value: "Technical Support Engineer", label: "Technical Support Engineer" },
  { value: "Network Engineer", label: "Network Engineer" },
  { value: "Procurement Specialist", label: "Procurement Specialist" },
  { value: "Legal Advisor", label: "Legal Advisor" },
  { value: "Quality Assurance Manager", label: "Quality Assurance Manager" },
  { value: "Training Specialist", label: "Training Specialist" }
];

export default roles;
